--1que
select FIRST_NAME As WORKER_NAME
from Worker

--2.que
SELECT UPPER(FIRST_NAME) AS FIRST_NAME
FROM Worker;
3--3.que
SELECT DISTINCT DEPARTMENT
FROM Worker;
--4.que
SELECT SUBSTRING(FIRST_NAME, 1, 3) AS FIRST_THREE_CHARS
FROM Worker;
--5.que
SELECT CHARINDEX('a', FIRST_NAME) AS POSITION
FROM Worker
WHERE FIRST_NAME = 'Amitabh';
--6.que
SELECT RTRIM(FIRST_NAME) AS TRIMMED_NAME
FROM Worker;
--7.que
SELECT LTRIM(DEPARTMENT) AS TRIMMED_DEPARTMENT
FROM Worker;
-- 8.que
select DISTINCT DEPARTMENT,LEN(DEPARTMENT)
from Worker;
--9.que
SELECT REPLACE(FIRST_NAME, 'a', 'A') AS UPDATED_NAME
FROM Worker;
--10.que
SELECT FIRST_NAME + ' ' + LAST_NAME AS COMPLETE_NAME
FROM Worker;
--11.que
SELECT *
FROM Worker
ORDER BY FIRST_NAME ASC;
--12.que
SELECT *
FROM Worker
ORDER BY FIRST_NAME ASC,DEPARTMENT DESC;
--13.que
select * from 
Worker
where FIRST_NAME IN ('Vipul','Satish')
--14.que
select * from 
Worker
where FIRST_NAME NOT IN ('Vipul','Satish')
--15.que
select * from Worker
where DEPARTMENT ='Admin'

--16.que
SELECT *
FROM Worker
WHERE FIRST_NAME LIKE '%a%';

--17.que
SELECT *
FROM Worker
WHERE FIRST_NAME LIKE '%a'

--18.que
SELECT *
FROM Worker
WHERE FIRST_NAME LIKE '%h'
AND LEN(FIRST_NAME) = 6;
--19.que
SELECT *
FROM Worker
WHERE SALARY BETWEEN 100000 AND 500000;
--20.que
SELECT *
FROM Worker
WHERE MONTH(JOINING_DATE) = 2
AND YEAR(JOINING_DATE) = 2014;
--21.que
SELECT FIRST_NAME
FROM Worker
WHERE SALARY BETWEEN 50000 AND 100000;

--22.que
SELECT DEPARTMENT, COUNT(*) AS TOTAL_WORKERS
FROM Worker
GROUP BY DEPARTMENT
ORDER BY TOTAL_WORKERS DESC;
--23.que
SELECT W.*
FROM Worker W
JOIN Title T ON W.WORKER_ID = T.WORKER_REF_ID
WHERE T.WORKER_TITLE = 'Manager';
--24.que
SELECT GETDATE() AS CURRENT_DATE_TIME;
--25.que
SELECT TOP 10 *
FROM Worker;